# Generated by Django 6.0.2 on 2026-03-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('algorithm', models.CharField(choices=[('rsa', 'RSA'), ('ec', 'Elliptic Curve'), ('eddsa', 'EdDSA'), ('x25519', 'X25519'), ('x448', 'X448')], max_length=20)),
                ('curve_name', models.CharField(blank=True, max_length=64)),
                ('key_size', models.PositiveIntegerField(blank=True, null=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('private_key_pem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateSigningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subject', models.JSONField(default=dict)),
                ('csr_pem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('private_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='csrs', to='pki.privatekey')),
            ],
        ),
        migrations.CreateModel(
            name='SignedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('certificate_pem', models.TextField()),
                ('serial_number', models.CharField(max_length=128)),
                ('not_valid_before', models.DateTimeField()),
                ('not_valid_after', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_certificates', to='pki.certificatesigningrequest')),
                ('private_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='pki.privatekey')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('certification_depth', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='pki.certificateauthority')),
                ('private_key', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_authority', to='pki.privatekey')),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_authority', to='pki.signedcertificate')),
            ],
        ),
    ]
