# Generated by Django 6.0.2 on 2026-03-02 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pki_certificate_authorities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificatesigningrequest',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pki_csrs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatekey',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pki_private_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signedcertificate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pki_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='certificateauthority',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_ca_name_per_owner'),
        ),
    ]
