# Generated by Django 6.0.2 on 2026-03-02 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0002_certificateauthority_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedcertificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='pki.certificateauthority'),
        ),
    ]
