# Generated by Django 6.0.2 on 2026-03-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0003_signedcertificate_issued_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_ca', models.BooleanField(default=False)),
                ('path_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('days_valid', models.PositiveIntegerField(default=365)),
                ('key_algorithm', models.CharField(default='rsa', max_length=20)),
                ('curve_name', models.CharField(blank=True, default='secp256r1', max_length=64)),
                ('key_size', models.PositiveIntegerField(blank=True, default=2048, null=True)),
                ('public_exponent', models.PositiveIntegerField(default=65537)),
                ('ku_digital_signature', models.BooleanField(default=True)),
                ('ku_content_commitment', models.BooleanField(default=False)),
                ('ku_key_encipherment', models.BooleanField(default=True)),
                ('ku_data_encipherment', models.BooleanField(default=False)),
                ('ku_key_agreement', models.BooleanField(default=False)),
                ('ku_key_cert_sign', models.BooleanField(default=False)),
                ('ku_crl_sign', models.BooleanField(default=False)),
                ('ku_encipher_only', models.BooleanField(default=False)),
                ('ku_decipher_only', models.BooleanField(default=False)),
                ('ku_critical', models.BooleanField(default=True)),
                ('eku_server_auth', models.BooleanField(default=True)),
                ('eku_client_auth', models.BooleanField(default=False)),
                ('eku_code_signing', models.BooleanField(default=False)),
                ('eku_email_protection', models.BooleanField(default=False)),
                ('eku_time_stamping', models.BooleanField(default=False)),
                ('eku_ocsp_signing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pki_certificate_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_profile_name_per_owner')],
            },
        ),
    ]
