# Generated by Django 6.0.2 on 2026-03-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0004_certificateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateprofile',
            name='common_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certificateprofile',
            name='country_name',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='certificateprofile',
            name='email_address',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='certificateprofile',
            name='locality_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='certificateprofile',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certificateprofile',
            name='organizational_unit_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certificateprofile',
            name='state_or_province_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
