# Generated by Django 6.0.2 on 2026-03-02 20:59

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0005_certificateprofile_subject_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatesigningrequest',
            name='private_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='csrs', to='pki.privatekey'),
        ),
        migrations.AlterField(
            model_name='privatekey',
            name='private_key_pem',
            field=encrypted_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='signedcertificate',
            name='private_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='pki.privatekey'),
        ),
    ]
